### ISSUE TITLE
Does not work with selected features in QGIS 2.99

### ISSUE THREAD

**Issue by havatv** [havatv/qgisnnjoinplugin#9]
When trying to work on selected features in QGIS 2.99, NNJoin fails with the following error message:

    AttributeError: 'QgsVectorLayer' object has no attribute 'selectedFeaturesIterator'

**Comment by havatv** [comment]
In QGIS 3 (2.99), selectedFeaturesIterator has been removed and getSelectedFeatures has to be used instead.  Fixed.
